version: "3"

services: 
    db:
        image: postgres:12
        container_name: updatetech_db
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - updatetech-db:/var/lib/postgresql/data
    server:
        container_name: updatetech_server
        image: docker.pkg.github.com/mubarak117136/updatetech/updatetech:dev
        environment:
            - DJANGO_SETTINGS_MODULE:updatetech.settings.dev
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./:/app
        ports:
            - "8000:8000"
        depends_on: 
            - db
volumes: 
    updatetech-db: