version: "3"

services: 
    db:
        image: postgres:12
        container_name: updatetech_db
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - updatetech-db:/var/lib/postgresql/data
    server:
        container_name: updatetech_server
        image: docker.pkg.github.com/mubarak117136/updatetech/updatetech:dev
        environment:
            - DJANGO_SETTINGS_MODULE:updatetech.settings.production
        command: gunicorn -w 3 updatetech.wsgi -b 0.0.0.0:8000
        volumes:
            - ./server/.env:/app/server/.env
            - ./server/betop/static:/app/server/betop/static
            - ./server/betop/media:/app/server/betop/media
            - ./server/socket:/app/server/socket
        ports:
            - "8000:8000"
volumes: 
    updatetech-db: