# Generated by Django 3.1.2 on 2021-10-13 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Invoice name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('invoice_from', models.TextField(verbose_name='Invoice From')),
                ('bill_to', models.TextField(verbose_name='Bill to')),
                ('ship_to', models.TextField(verbose_name='Ship to')),
                ('date', models.DateField(verbose_name='Creation date')),
                ('due_date', models.DateField(verbose_name='Due date')),
                ('notes', models.TextField(verbose_name='Notes')),
                ('terms', models.TextField(verbose_name='Terms')),
                ('status', models.CharField(choices=[(0, 'Due'), (1, 'Unpaid'), (2, 'Paid')], default=1, max_length=50, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('quantity', models.SmallIntegerField(verbose_name='Quantity')),
                ('rate', models.IntegerField(verbose_name='Rate')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.invoice', verbose_name='Invoice')),
            ],
        ),
    ]
